version: "3.9"

services:
  grafana:
    image: "grafana/grafana:8.4.2"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  loki:
    image: "grafana/loki:2.4.2"
    ports:
      - "3100:3100"

  promtail:
    image: "grafana/promtail:2.4.2"
    volumes:
      - logs_dir:/tmp/log
      - ./promtail.yml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml

  flog:
    image: "mingrammer/flog:0.4.3"
    command: -f json -t log -o /tmp/log/json.log -d 200ms -w -l
    volumes:
      - logs_dir:/tmp/log

volumes:
  logs_dir: