version: "3.9"

services:
  grafana:
    image: "grafana/grafana:8.4.2"
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  loki:
    image: "grafana/loki:2.4.2"
    command: --config.file=/mnt/config/loki.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/mnt/config/loki.yml
      - ./rules.yml:/etc/loki/rules/fake/rules.yml

volumes:
  logs_dir: